all:
	g++ -O3 -o curtis_part1.main curtis_part1.cpp
	g++ -O3 -o curtis_part2.main curtis_part2.cpp
	g++ -O3 -o curtis_part1_optimized.main curtis_part1_optimized.cpp
	g++ -O3 -o curtis_part2_optimized.main curtis_part2_optimized.cpp
